version: '3.3'
services:
  post_db:
    image: mongo:${version_mongodb}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db

  ui:
    image: ${USER_NAME}/ui:${version_modules}
    ports:
      - ${ui_port}
    networks:
      - front_net

  post:
    image: ${USER_NAME}/post:${version_modules}
    networks:
      - back_net
      - front_net

  comment:
    image: ${USER_NAME}/comment:${version_modules}
    networks:
      - back_net
      - front_net

  prometheus:
    image: ${USER_NAME}/prometheus:${version_prom}
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - back_net
      - front_net

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - back_net
      - front_net

volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
  front_net:

